# Generated by Django 5.2.1 on 2026-06-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productitem',
            options={'ordering': ('size',), 'verbose_name': 'Product Variant', 'verbose_name_plural': 'Product Variants'},
        ),
        migrations.AddField(
            model_name='productitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional variant price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='color',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], max_length=5),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
